version: '3.7'

services: 

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hzjio_blog_dev
      MYSQL_ROOT_PASSWORD: 123
    container_name: blog_database
    volumes: 
      - /www/db/hzjio_blog_dev:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - 80:80
    container_name: blog_nginx
    restart: unless-stopped
    volumes: 
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/deafult.conf

  server:
    ports:
      - 3000:3000
    build: 
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - database
    links:  
      - database
    container_name: blog_server

volumes:
  dist: