version: '3.7'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: blog_jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '/www/jenkins_home:/var/jenkins_home'