version: '3.7'

services: 

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hzjio_blog_dev
      MYSQL_ROOT_PASSWORD: 123
    container_name: blog_database
    volumes: 
      - /www/db/hzjio_blog_dev:/var/lib/mysql

  nginx:
    build:
      context: ../
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    container_name: blog_nginx
    restart: unless-stopped