version: '3.7'

services: 

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: hzjio_blog_dev
      MYSQL_ROOT_PASSWORD: 123
    container_name: blog_database
    volumes: 
      - /www/db/hzjio_blog_dev:/var/lib/mysql

  nginx:
    build:
      context: ../
      dockerfile: nginx.Dockerfile
    container_name: blog_nginx
    restart: unless-stopped
    network_mode: "host"
    

  server:
    ports:
      - 3000:3000
    restart: always
    build: 
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - database
    links:  
      - database
    container_name: blog_server